CREATE DATABASE TRANSACTIONS
CREATE TABLE Accounts ( 
AccountID INT PRIMARY KEY,
AccountName NVARCHAR(50),
Balance DECIMAL(10, 2)
);
---1----
BEGIN TRANSACTION

INSERT INTO Accounts
VALUES(4,'TOMAS',-5000)

IF (SELECT BALANCE FROM Accounts WHERE AccountID=4)<0
BEGIN
ROLLBACK
END
ELSE
BEGIN
COMMIT
END
SELECT * FROM Accounts
----2---
BEGIN TRANSACTION
UPDATE Accounts SET Balance=Balance-500 WHERE AccountID=1
UPDATE Accounts SET Balance=Balance+500 WHERE AccountID=2
IF @@ERROR=0
COMMIT
ELSE ROLLBACK

----3-----
CREATE TABLE TransactionLog
(LogID INT PRIMARY KEY IDENTITY(1,1),
TransactionTime DATETIME DEFAULT GETDATE(),
Action VARCHAR(255),
Status VARCHAR(50),
Errormssage VARCHAR(MAX)
)

BEGIN TRY
 BEGIN TRANSACTION
 UPDATE Accounts SET AccountName='EDA' WHERE AccountID=2

 INSERT INTO TransactionLog(Action,Status)
 VALUES('UPDATED','Success')

 COMMIT TRANSACTION

END TRY
BEGIN CATCH

 ROLLBACK TRANSACTION
 INSERT INTO TransactionLog(Action,Status,Errormssage)
 VALUES('UPDATED','fail',ERROR_MESSAGE())
END CATCH

SELECT * FROM Accounts
SELECT * FROM TransactionLog
-----4---

----5----
CREATE TABLE Orders ( 
OrderID INT PRIMARY KEY, 
CustomerID INT,
OrderDate DATE
);
CREATE TABLE OrderLog ( 
LogID INT IDENTITY(1,1) PRIMARY KEY,
OrderID INT,
LogDate DATETIME DEFAULT GETDATE()
);

CREATE TRIGGER TRG_AFT_INSERT
ON ACCOUNTS
AFTER INSERT
AS 
BEGIN
INSERT INTO TransactionLog(Action,Status)
VALUES('INSERTED ACCOUNT','Success')
END